export const ADD_INPUT_CARD = 'ADD_INPUT_CARD';
export type ADD_INPUT_CARD = typeof ADD_INPUT_CARD;

export const REMOVE_INPUT_CARD = 'REMOVE_INPUT_CARD';
export type REMOVE_INPUT_CARD = typeof REMOVE_INPUT_CARD;

export const UPDATE_INPUT_CARD = 'UPDATE_INPUT_CARD';
export type UPDATE_INPUT_CARD = typeof UPDATE_INPUT_CARD;

// export const ADD_CREATURE_CARD = 'ADD_CREATURE_CARD';
// export type ADD_CREATURE_CARD = typeof ADD_CREATURE_CARD;
//
// export const REMOVE_CREATURE_CARD = 'REMOVE_CREATURE_CARD';
// export type REMOVE_CREATURE_CARD = typeof REMOVE_CREATURE_CARD;
//
// export const UPDATE_CREATURE_CARD = 'UPDATE_CREATURE_CARD';
// export type UPDATE_CREATURE_CARD = typeof UPDATE_CREATURE_CARD;

export const CREATURE_CARD = 'CREATURE_CARD';
export type CREATURE_CARD = typeof CREATURE_CARD;

export const DRAW_CARD = 'DRAW_CARD';
export type DRAW_CARD = typeof DRAW_CARD;

export const UPDATE_NUMERIC_SETTING = 'UPDATE_NUMERIC_SETTING';
export type UPDATE_NUMERIC_SETTING = typeof UPDATE_NUMERIC_SETTING;

export const UPDATE_DRAW_MULLIGAN = 'UPDATE_DRAW_MULLIGAN';
export type UPDATE_DRAW_MULLIGAN = typeof UPDATE_DRAW_MULLIGAN;

export const MAX_DRAW_AMOUNT = 30;
export const MIN_DRAW_AMOUNT = 3;

export const CALCULATE_DRAW = 'CALCULATE_DRAW';
export type CALCULATE_DRAW = typeof CALCULATE_DRAW;

export const CALCULATE_PING = 'CALCULATE_PING';
export type CALCULATE_PING = typeof CALCULATE_PING;