export const ADD_DRAW_CARD = 'ADD_DRAW_CARD';
export type ADD_DRAW_CARD = typeof ADD_DRAW_CARD;

export const REMOVE_DRAW_CARD = 'REMOVE_DRAW_CARD';
export type REMOVE_DRAW_CARD = typeof REMOVE_DRAW_CARD;

export const UPDATE_DRAW_CARD = 'UPDATE_DRAW_CARD';
export type UPDATE_DRAW_CARD = typeof UPDATE_DRAW_CARD;

export const ADD_CREATURE_CARD = 'ADD_CREATURE_CARD';
export type ADD_CREATURE_CARD = typeof ADD_CREATURE_CARD;

export const REMOVE_CREATURE_CARD = 'REMOVE_CREATURE_CARD';
export type REMOVE_CREATURE_CARD = typeof REMOVE_CREATURE_CARD;

export const UPDATE_CREATURE_CARD = 'UPDATE_CREATURE_CARD';
export type UPDATE_CREATURE_CARD = typeof UPDATE_CREATURE_CARD;

export const UPDATE_DRAW_AMOUNT = 'UPDATE_DRAW_AMOUNT';
export type UPDATE_DRAW_AMOUNT = typeof UPDATE_DRAW_AMOUNT;

export const UPDATE_DRAW_MULLIGAN = 'UPDATE_DRAW_MULLIGAN';
export type UPDATE_DRAW_MULLIGAN = typeof UPDATE_DRAW_MULLIGAN;

export const MAX_DRAW_AMOUNT = 30;
export const MIN_DRAW_AMOUNT = 3;

export const CALCULATE_DRAW = 'CALCULATE_DRAW';
export type CALCULATE_DRAW = typeof CALCULATE_DRAW;

export const CALCULATE_PING = 'CALCULATE_PING';
export type CALCULATE_PING = typeof CALCULATE_PING;